### ISSUE TITLE
Having issues with authentication

### ISSUE THREAD

**Issue by surendrakoritala** [microsoftgraph/react-officeuifabric-sample#4]
I am getting 401 authentication error. As the call to authProvider function is returning undefined access token. On one post I saw it's issues with v1.0 end point. Did anyone have issues with authentication with aad?

**Comment by jasonjoh** [comment]
Thanks for your interest in Microsoft Graph! We are archiving this sample, so I'm closing this issue. Our recommendation for React UI components is to use the [Microsoft Graph Toolkit](https://docs.microsoft.com/graph/toolkit/overview). We apologize for any inconvenience.
